[alias] # command aliases
install_soroban = "install --git https://github.com/AhaLabs/soroban-tools --rev c7fb7e08ba8efa9828d9df863d991558f269e35b --root ./target soroban-cli --debug  --features opt"
b = "build --target wasm32-unknown-unknown --release"
